###
### Sudo required
###
sudo: required


###
### Set language
###
language: python


###
### Python Build Matrix
###
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"


###
### Install required software
###
before_install:
  - sudo apt-get update
  - sudo apt-get install -y pep8 bash


###
### Run tests
###
script:
  # Coding conventions
  - pep8 --max-line-length=100 bin/vhost_gen.py

  # Basic program checks
  - ./bin/vhost_gen.py -h
  - ./bin/vhost_gen.py -v
  - ./bin/vhost_gen.py -p ./ -n name -t etc/templates/
  - ./bin/vhost_gen.py -p ./ -n name -t etc/templates/ -c etc/conf.yml

  # Fuzzying
  - .ci/fuzzy.sh
