###
### Sudo required
###
dist: trusty
sudo: required
#sudo: false


###
### Set language
###
language: python


###
### Python Build Matrix
###
python:
  - "2.7"
  - "3.5"
  - "3.6"


###
### Install required software
###
before_install:
  # Install required tools
  #- sudo apt-get update
  #- sudo apt-get install -y pep8 pylint

  # Create directories
  - sudo rm -rf /etc/nginx/conf.d || true
  - sudo rm -rf /etc/httpd/conf.d || true
  - sudo rm -rf /etc/apache2/conf.d || true

  - sudo mkdir -p /etc/nginx/conf.d
  - sudo mkdir -p /etc/httpd/conf.d
  - sudo mkdir -p /etc/apache2/conf.d

  - sudo mkdir -p /var/log/nginx
  - sudo mkdir -p /var/log/httpd
  - sudo mkdir -p /var/log/apache2

  # Add open permissions
  - sudo chmod 0777 /etc/nginx/conf.d
  - sudo chmod 0777 /etc/httpd/conf.d
  - sudo chmod 0777 /etc/apache2/conf.d

  - sudo chmod 0777 /var/log/nginx
  - sudo chmod 0777 /var/log/httpd
  - sudo chmod 0777 /var/log/apache2


###
###
###
install:
  # Install
  - pip install -r requirements.txt
  - pip install pylint flake8 pycodestyle
  # Show versions
  - pylint --version || true
  - flake8 --version || true
  - pycodestyle --version || true


###
### Show versions
###
before_script:
  # Show versions
  - ./bin/vhost-gen --help
  - ./bin/vhost-gen --version


###
### Run tests
###
script:
  # Coding conventions
  - make lint

  # Outputs
  - make test

  # Saving (nginx)
  - ./bin/vhost-gen -p ./ -n name -t etc/templates/ -c etc/conf.yml -s
  - cat /etc/nginx/conf.d/name.conf

  # Saving (nginx example)
  - ./bin/vhost-gen -p ./ -n name -t etc/templates/ -c examples/conf.nginx.yml -s
  - cat /etc/nginx/conf.d/name.conf

  # Saving (apache22 example)
  - ./bin/vhost-gen -p ./ -n name -t etc/templates/ -c examples/conf.apache22.yml -s
  - cat /etc//httpd/conf.d/name.conf

  # Saving (apache24 example)
  - ./bin/vhost-gen -p ./ -n name -t etc/templates/ -c examples/conf.apache24.yml -s
  - cat /etc/apache2/conf.d/name.conf

  # Find flaws via fuzzying (before installing config files)
  - time .ci/fuzzy.sh

  # Find flaws via fuzzying (after installing config files)
  - sudo make install
  - time .ci/fuzzy.sh
